### ISSUE TITLE
Can someone tell me if I have this correct in the server?

### ISSUE THREAD

**Issue by benjamin25015** [Triang3l/WebQuake#38]
![quake1](https://user-images.githubusercontent.com/42532850/54162688-0844a400-441c-11e9-896e-2334d00160ee.JPG)
![quake2](https://user-images.githubusercontent.com/42532850/54162694-11ce0c00-441c-11e9-9e46-7c5a822e7044.JPG)

Thanks again, 

When I launch from just the index file, I get this screen:

![quake4](https://user-images.githubusercontent.com/42532850/54162900-dbdd5780-441c-11e9-84e3-e9a56aadcdc1.JPG)

I am not sure of the file structure, or the instructions are somewhat vague on how to implement the game. 

I found some information on the original discussion:

> 2013-02-11

 20:12:14
Spirit
Administrator

Paul: For example like this

/dir/
/dir/WebQuake/
/dir/WebQuake.htm
/dir/id1/
/dir/id1/pak0.pak
/dir/rogue/
/dir/randommod/

Make sure everything is lowercase (unless you are on a Windows server).

Andrew, mods work. :) Try http://www.quaddicted.com/stuff/WebQuak … me%20qdqst or http://www.quaddicted.com/stuff/WebQuak … me%20czg07 (that one crashes after the start map) or http://www.quaddicted.com/stuff/WebQuak … me%20quoth (I have not tested that one yet). 

> 

This looks similar to what I have, but it still throws an error.

**Comment by SpiritQuaddicted** [comment]
You must launch the server and then access it via http or https, right now you are trying to load the files directly (bypassing the web server).

This is not worth using if you simply want to play Quake on your local machine. Use http://quakespasm.sourceforge.net/download.htm for that.

**Comment by Triang3l** [comment]
That's a limitation of the way WebQuake reads files — it uses real HTTP error codes to check request status, and it also uses the Range header to fetch specific files from .pak archives. So yes, you need to go to `http://127.0.0.1/quake1/index.htm` in your web browser while the server is running, as when you are actually hosting a website on your PC, rather than opening the HTML file itself. Also you need to put `quake1` in `htdocs`, not in the root directory of Abyss itself.
